Algoritmo "SOM_SUB_MUL_DEBUG"


Var
// Seção de Declarações das variáveis
     n1, n2, total : inteiro

Inicio
// Saída de dados

// Entrada de dados
   escreva("Digite um número: ")
   leia(n1)
   
   escreva("Digite outro número: ")
   leia (n2)
   
// Processamento
   total <- n1 + n2
   escreval("Soma = ", total)
   
   total <- n1 - n2
   escreval("Subtração = ", total)
   
   total <- n1 * n2
   escreval("Multiplicação = ", total)


Fimalgoritmo